import { 
  UserRole, Reservation, ReservationInquiry, ReservationStatus, PaymentMethod, BookingChannel, InquiryStatus,
  BasePrice, Season, SeasonStatus, PriceAdjustmentType, PriceHistory,
  Channel, ChannelType, ChannelStatus, ChannelPerformance,
  Invoice, InvoiceType, InvoiceStatus, InvoiceItem, AdditionalBilling, Refund, CreditNote,
  Service, ServiceCategory, PricingModel, ServiceStatus, ServiceRequest, ServiceRequestStatus,
  HotelPolicy, PolicyType, CancellationPolicy, PenaltyType, OverbookingPolicy,
  RoomViewType, MealPlan, MealPlanCode
} from '../types'
import { LayoutDashboard, Hotel, Users, Bed, CalendarCheck, DollarSign, Settings, Handshake, Receipt, Utensils, BarChart3, ShieldCheck, ChefHat } from 'lucide-react'

export const NAV_LINKS = [
  {
    name: 'Dashboard',
    path: '/admin-dashboard',
    icon: LayoutDashboard,
    roles: [UserRole.Admin, UserRole.Receptionist],
  },
  {
    name: 'Rooms',
    path: '/rooms',
    icon: Hotel,
    roles: [UserRole.Admin, UserRole.Receptionist],
  },
  {
    name: 'Housekeeping',
    path: '/housekeeping',
    icon: Bed,
    roles: [UserRole.Admin, UserRole.Housekeeping],
  },
  {
    name: 'Guests',
    path: '/guests',
    icon: Users,
    roles: [UserRole.Admin, UserRole.Receptionist],
  },
  {
    name: 'Reservations',
    path: '/reservations',
    icon: CalendarCheck,
    roles: [UserRole.Admin, UserRole.Receptionist],
  },
  {
    name: 'Pricing',
    path: '/pricing',
    icon: DollarSign,
    roles: [UserRole.Admin],
  },
  {
    name: 'Taxes',
    path: '/taxes',
    icon: Receipt,
    roles: [UserRole.Admin],
  },
  {
    name: 'Currencies',
    path: '/currencies',
    icon: BarChart3,
    roles: [UserRole.Admin],
  },
  {
    name: 'Channels',
    path: '/channels',
    icon: Handshake,
    roles: [UserRole.Admin],
  },
  {
    name: 'Invoicing',
    path: '/invoicing',
    icon: Receipt,
    roles: [UserRole.Admin, UserRole.Receptionist],
  },
  {
    name: 'Services',
    path: '/services',
    icon: Utensils,
    roles: [UserRole.Admin, UserRole.Receptionist],
  },
  {
    name: 'Meal Plans',
    path: '/meals',
    icon: ChefHat,
    roles: [UserRole.Admin, UserRole.Receptionist],
  },
  {
    name: 'Events',
    path: '/events',
    icon: CalendarCheck,
    roles: [UserRole.Admin, UserRole.Receptionist],
  },
  {
    name: 'Policies',
    path: '/policies',
    icon: ShieldCheck,
    roles: [UserRole.Admin],
  },
  {
    name: 'Reports',
    path: '/reports',
    icon: BarChart3,
    roles: [UserRole.Admin],
  },
  {
    name: 'Settings',
    path: '/settings',
    icon: Settings,
    roles: [UserRole.Admin],
  },
]

// Mock Data for demonstration
export const MOCK_ROOM_VIEW_TYPES: RoomViewType[] = [
  {
    id: 'VT-SEA',
    name: 'Sea View',
    description: 'Rooms facing the ocean or beach with unobstructed sea views.',
    exampleUsage: 'Deluxe Room – Sea View',
    surchargeType: 'Percentage',
    surchargeValue: 25,
    active: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'VT-GARDEN',
    name: 'Garden View',
    description: 'Rooms overlooking the landscaped gardens or greenery.',
    exampleUsage: 'Standard Room – Garden View',
    surchargeType: 'Percentage',
    surchargeValue: 10,
    active: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'VT-CITY',
    name: 'City View',
    description: 'Rooms offering a view of the city skyline or streets.',
    exampleUsage: 'Executive Suite – City View',
    surchargeType: 'Flat',
    surchargeValue: 15,
    active: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'VT-POOL',
    name: 'Pool View',
    description: 'Rooms overlooking the swimming pool area.',
    exampleUsage: 'Superior Room – Pool View',
    surchargeType: 'Percentage',
    surchargeValue: 12,
    active: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'VT-MOUNTAIN',
    name: 'Mountain View',
    description: 'Rooms facing hills or mountain ranges.',
    exampleUsage: 'Suite – Mountain View',
    surchargeType: 'Percentage',
    surchargeValue: 18,
    active: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'VT-COURTYARD',
    name: 'Courtyard View',
    description: 'Rooms facing the inner courtyard or lobby area.',
    exampleUsage: 'Classic Room – Courtyard View',
    surchargeType: 'Flat',
    surchargeValue: 8,
    active: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'VT-PARTIALSEA',
    name: 'Partial Sea View',
    description: 'Rooms with limited or side-angle ocean visibility.',
    exampleUsage: 'Deluxe Partial Sea View Room',
    surchargeType: 'Percentage',
    surchargeValue: 15,
    active: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'VT-INTERIOR',
    name: 'Interior View',
    description: 'Rooms without external scenic view, may face an interior wall or corridor.',
    exampleUsage: 'Budget Room – No View',
    surchargeType: 'Flat',
    surchargeValue: 0,
    active: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
]

export const MOCK_MEAL_PLANS: MealPlan[] = [
  {
    id: 'MP-RO',
    code: MealPlanCode.RO,
    name: 'Room Only',
    description: 'No meals are included in the booking.',
    markupType: 'Flat',
    markupValue: 0,
    active: true,
    defaultForRoomTypes: ['Standard King', 'Standard Twin'],
    notes: 'Ideal for guests who prefer dining outside the hotel.',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'MP-BB',
    code: MealPlanCode.BB,
    name: 'Bed & Breakfast',
    description: 'Includes breakfast only.',
    markupType: 'Flat',
    markupValue: 20,
    active: true,
    defaultForRoomTypes: ['Deluxe Queen'],
    notes: 'Best for short or business stays.',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'MP-HB',
    code: MealPlanCode.HB,
    name: 'Half Board',
    description: 'Includes breakfast and dinner.',
    markupType: 'Percentage',
    markupValue: 20,
    active: true,
    defaultForRoomTypes: ['Suite'],
    notes: 'Popular for mid-range packages.',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'MP-FB',
    code: MealPlanCode.FB,
    name: 'Full Board',
    description: 'Includes breakfast, lunch, and dinner.',
    markupType: 'Percentage',
    markupValue: 35,
    active: true,
    defaultForRoomTypes: ['Suite'],
    notes: 'Preferred by families or long-stay guests.',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
]

export const MOCK_ROOMS = [
  {
    id: 'R001',
    number: '101',
    type: 'Standard King',
    capacity: 2,
    price: 150,
    area: 'Floor 1',
    amenities: ['WiFi', 'TV', 'AC'],
    status: 'Occupied',
    imageUrl: 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    viewTypeId: 'VT-CITY',
    viewTypeName: 'City View',
    mealPlanCode: MealPlanCode.RO,
  },
  {
    id: 'R002',
    number: '102',
    type: 'Standard King',
    capacity: 2,
    price: 150,
    area: 'Floor 1',
    amenities: ['WiFi', 'TV', 'AC'],
    status: 'Cleaning in Progress',
    imageUrl: 'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    viewTypeId: 'VT-COURTYARD',
    viewTypeName: 'Courtyard View',
    mealPlanCode: MealPlanCode.RO,
  },
  {
    id: 'R003',
    number: '103',
    type: 'Deluxe Queen',
    capacity: 3,
    price: 200,
    area: 'Floor 1',
    amenities: ['WiFi', 'TV', 'AC', 'Mini Bar'],
    status: 'Available',
    imageUrl: 'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    viewTypeId: 'VT-GARDEN',
    viewTypeName: 'Garden View',
    mealPlanCode: MealPlanCode.BB,
  },
  {
    id: 'R004',
    number: '201',
    type: 'Suite',
    capacity: 4,
    price: 350,
    area: 'Floor 2',
    amenities: ['WiFi', 'TV', 'AC', 'Mini Bar', 'Jacuzzi'],
    status: 'Reserved',
    imageUrl: 'https://images.pexels.com/photos/262048/pexels-photo-262048.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    viewTypeId: 'VT-SEA',
    viewTypeName: 'Sea View',
    mealPlanCode: MealPlanCode.FB,
  },
  {
    id: 'R005',
    number: '202',
    type: 'Standard Twin',
    capacity: 2,
    price: 120,
    area: 'Floor 2',
    amenities: ['WiFi', 'TV', 'AC'],
    status: 'Under Maintenance',
    imageUrl: 'https://images.pexels.com/photos/271639/pexels-photo-271639.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    viewTypeId: 'VT-INTERIOR',
    viewTypeName: 'Interior View',
    mealPlanCode: MealPlanCode.RO,
  },
  {
    id: 'R006',
    number: '203',
    type: 'Deluxe Queen',
    capacity: 3,
    price: 200,
    area: 'Floor 2',
    amenities: ['WiFi', 'TV', 'AC', 'Mini Bar'],
    status: 'Dirty',
    imageUrl: 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    viewTypeId: 'VT-POOL',
    viewTypeName: 'Pool View',
    mealPlanCode: MealPlanCode.HB,
  },
]

export const MOCK_GUESTS = [
  {
    id: 'G001',
    fullName: 'Alice Wonderland',
    email: 'alice@example.com',
    phone: '+1234567890',
    country: 'USA',
    gender: 'Female',
    documentType: 'Passport',
    documentNumber: 'AB1234567',
    visitCount: 5,
    lifetimeSpending: 2500,
    status: 'VIP',
    avatarUrl: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 'G002',
    fullName: 'Bob The Builder',
    email: 'bob@example.com',
    phone: '+1987654321',
    country: 'Canada',
    gender: 'Male',
    documentType: 'NIC',
    documentNumber: 'CD9876543',
    visitCount: 1,
    lifetimeSpending: 150,
    status: 'New',
    avatarUrl: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 'G003',
    fullName: 'Charlie Chaplin',
    email: 'charlie@example.com',
    phone: '+44712345678',
    country: 'UK',
    gender: 'Male',
    documentType: 'Passport',
    documentNumber: 'EF1122334',
    visitCount: 3,
    lifetimeSpending: 800,
    status: 'Regular',
    avatarUrl: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 'G004',
    fullName: 'Diana Prince',
    email: 'diana@example.com',
    phone: '+61401234567',
    country: 'Australia',
    gender: 'Female',
    documentType: 'Passport',
    documentNumber: 'GH5566778',
    visitCount: 7,
    lifetimeSpending: 3200,
    status: 'VIP',
    avatarUrl: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 'G005',
    fullName: 'Eve Harrington',
    email: 'eve@example.com',
    phone: '+33612345678',
    country: 'France',
    gender: 'Female',
    documentType: 'NIC',
    documentNumber: 'IJ9988776',
    visitCount: 2,
    lifetimeSpending: 450,
    status: 'Regular',
    avatarUrl: 'https://images.pexels.com/photos/1065084/pexels-photo-1065084.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
]

export const MOCK_HOUSEKEEPING_TASKS = [
  {
    roomId: 'R002',
    roomNumber: '102',
    status: 'Cleaning in Progress',
    assignedTo: 'HK001',
    checklist: {
      cleanBathroom: true,
      changeBedSheets: false,
      replaceTowels: true,
      restockEssentials: false,
      floorCleaning: false,
      finalInspection: false,
    },
    lastUpdated: '2024-07-26T10:30:00Z',
  },
  {
    roomId: 'R006',
    roomNumber: '203',
    status: 'Dirty',
    assignedTo: undefined,
    checklist: {
      cleanBathroom: false,
      changeBedSheets: false,
      replaceTowels: false,
      restockEssentials: false,
      floorCleaning: false,
      finalInspection: false,
    },
    lastUpdated: '2024-07-26T09:00:00Z',
  },
  {
    roomId: 'R001',
    roomNumber: '101',
    status: 'Occupied', // Should not appear in housekeeping dashboard unless dirty after checkout
    assignedTo: undefined,
    checklist: {
      cleanBathroom: false,
      changeBedSheets: false,
      replaceTowels: false,
      restockEssentials: false,
      floorCleaning: false,
      finalInspection: false,
    },
    lastUpdated: '2024-07-25T14:00:00Z',
  },
]

export const MOCK_RESERVATIONS: Reservation[] = [
  {
    id: 'RES001',
    reservationNumber: 'RES-2024-001',
    guestId: 'G001',
    guestName: 'Alice Wonderland',
    guestEmail: 'alice@example.com',
    guestPhone: '+1234567890',
    roomId: 'R001',
    roomNumber: '101',
    roomType: 'Standard King',
    mealPlanCode: MealPlanCode.BB,
    checkInDate: '2024-07-20',
    checkOutDate: '2024-07-25',
    adults: 2,
    children: 0,
    channel: BookingChannel.Website,
    status: ReservationStatus.CheckedIn,
    baseRate: 750,
    seasonalPricing: 50,
    channelPricing: 0,
    tax: 80,
    totalAmount: 880,
    paidAmount: 880,
    pendingAmount: 0,
    paymentMethod: PaymentMethod.Online,
    invoiceNumber: 'INV-2024-001',
    createdAt: '2024-07-15T10:00:00Z',
    updatedAt: '2024-07-20T14:00:00Z',
  },
  {
    id: 'RES002',
    reservationNumber: 'RES-2024-002',
    guestId: 'G002',
    guestName: 'Bob The Builder',
    guestEmail: 'bob@example.com',
    guestPhone: '+1987654321',
    roomId: 'R004',
    roomNumber: '201',
    roomType: 'Suite',
    mealPlanCode: MealPlanCode.FB,
    checkInDate: '2024-07-28',
    checkOutDate: '2024-08-02',
    adults: 2,
    children: 2,
    channel: BookingChannel.BookingCom,
    status: ReservationStatus.Confirmed,
    baseRate: 1750,
    seasonalPricing: 100,
    channelPricing: -87.5,
    tax: 176.25,
    totalAmount: 1938.75,
    paidAmount: 500,
    pendingAmount: 1438.75,
    paymentMethod: PaymentMethod.Card,
    invoiceNumber: 'INV-2024-002',
    createdAt: '2024-07-18T09:30:00Z',
    updatedAt: '2024-07-18T09:30:00Z',
  },
  {
    id: 'RES003',
    reservationNumber: 'RES-2024-003',
    guestId: 'G003',
    guestName: 'Charlie Chaplin',
    guestEmail: 'charlie@example.com',
    guestPhone: '+44712345678',
    roomId: 'R003',
    roomNumber: '103',
    roomType: 'Deluxe Queen',
    mealPlanCode: MealPlanCode.HB,
    checkInDate: '2024-07-15',
    checkOutDate: '2024-07-18',
    adults: 1,
    children: 0,
    channel: BookingChannel.WalkIn,
    status: ReservationStatus.CheckedOut,
    baseRate: 600,
    seasonalPricing: 30,
    channelPricing: 0,
    tax: 63,
    totalAmount: 693,
    paidAmount: 693,
    pendingAmount: 0,
    paymentMethod: PaymentMethod.Cash,
    invoiceNumber: 'INV-2024-003',
    createdAt: '2024-07-15T08:00:00Z',
    updatedAt: '2024-07-18T11:00:00Z',
  },
  {
    id: 'RES004',
    reservationNumber: 'RES-2024-004',
    guestId: 'G004',
    guestName: 'Diana Prince',
    guestEmail: 'diana@example.com',
    guestPhone: '+61401234567',
    roomId: 'R003',
    roomNumber: '103',
    roomType: 'Deluxe Queen',
    mealPlanCode: MealPlanCode.BB,
    checkInDate: '2024-08-05',
    checkOutDate: '2024-08-10',
    adults: 2,
    children: 0,
    channel: BookingChannel.Expedia,
    status: ReservationStatus.Confirmed,
    baseRate: 1000,
    seasonalPricing: 50,
    channelPricing: -50,
    tax: 100,
    totalAmount: 1100,
    paidAmount: 1100,
    pendingAmount: 0,
    paymentMethod: PaymentMethod.Online,
    createdAt: '2024-07-20T14:20:00Z',
    updatedAt: '2024-07-20T14:20:00Z',
  },
  {
    id: 'RES005',
    reservationNumber: 'RES-2024-005',
    guestId: 'G005',
    guestName: 'Eve Harrington',
    guestEmail: 'eve@example.com',
    guestPhone: '+33612345678',
    roomId: 'R005',
    roomNumber: '202',
    roomType: 'Standard Twin',
    mealPlanCode: MealPlanCode.RO,
    checkInDate: '2024-07-22',
    checkOutDate: '2024-07-24',
    adults: 1,
    children: 0,
    channel: BookingChannel.Phone,
    status: ReservationStatus.Cancelled,
    baseRate: 240,
    seasonalPricing: 10,
    channelPricing: 0,
    tax: 25,
    totalAmount: 275,
    paidAmount: 0,
    pendingAmount: 0,
    paymentMethod: PaymentMethod.Card,
    createdAt: '2024-07-19T16:00:00Z',
    updatedAt: '2024-07-21T10:00:00Z',
    notes: 'Cancelled by guest',
  },
]

export const MOCK_RESERVATION_INQUIRIES: ReservationInquiry[] = [
  {
    id: 'INQ001',
    guestName: 'John Doe',
    guestEmail: 'john@example.com',
    guestPhone: '+1234567890',
    checkInDate: '2024-08-15',
    checkOutDate: '2024-08-20',
    adults: 2,
    children: 1,
    preferredRoomType: 'Deluxe Queen',
    status: InquiryStatus.Pending,
    remarks: 'Looking for a family-friendly room',
    createdAt: '2024-07-25T10:00:00Z',
  },
  {
    id: 'INQ002',
    guestName: 'Jane Smith',
    guestEmail: 'jane@example.com',
    guestPhone: '+1987654321',
    checkInDate: '2024-09-01',
    checkOutDate: '2024-09-05',
    adults: 1,
    children: 0,
    preferredRoomType: 'Standard King',
    status: InquiryStatus.Converted,
    remarks: 'Business trip',
    createdAt: '2024-07-20T14:00:00Z',
    convertedToReservationId: 'RES004',
  },
  {
    id: 'INQ003',
    guestName: 'Mike Johnson',
    guestEmail: 'mike@example.com',
    guestPhone: '+44712345678',
    checkInDate: '2024-08-10',
    checkOutDate: '2024-08-12',
    adults: 3,
    children: 0,
    preferredRoomType: 'Suite',
    status: InquiryStatus.Rejected,
    remarks: 'No availability for requested dates',
    createdAt: '2024-07-18T09:00:00Z',
  },
]

// Pricing Mock Data
export const MOCK_BASE_PRICES: BasePrice[] = [
  {
    id: 'BP001',
    roomType: 'Standard King',
    basePrice: 150,
    maximumOccupancy: 2,
    currency: 'USD',
    updatedAt: '2024-07-01T10:00:00Z',
    updatedBy: 'Admin',
  },
  {
    id: 'BP002',
    roomType: 'Deluxe Queen',
    basePrice: 200,
    maximumOccupancy: 3,
    currency: 'USD',
    updatedAt: '2024-07-01T10:00:00Z',
    updatedBy: 'Admin',
  },
  {
    id: 'BP003',
    roomType: 'Suite',
    basePrice: 350,
    maximumOccupancy: 4,
    currency: 'USD',
    updatedAt: '2024-07-01T10:00:00Z',
    updatedBy: 'Admin',
  },
  {
    id: 'BP004',
    roomType: 'Standard Twin',
    basePrice: 120,
    maximumOccupancy: 2,
    currency: 'USD',
    updatedAt: '2024-07-01T10:00:00Z',
    updatedBy: 'Admin',
  },
]

export const MOCK_SEASONS: Season[] = [
  {
    id: 'SEASON001',
    name: 'Summer Peak',
    startDate: '2024-06-01',
    endDate: '2024-08-31',
    adjustmentType: PriceAdjustmentType.Percentage,
    adjustmentValue: 15,
    status: SeasonStatus.Active,
    createdAt: '2024-05-01T10:00:00Z',
    updatedAt: '2024-05-01T10:00:00Z',
  },
  {
    id: 'SEASON002',
    name: 'Holiday Season',
    startDate: '2024-12-20',
    endDate: '2025-01-05',
    adjustmentType: PriceAdjustmentType.Percentage,
    adjustmentValue: 25,
    status: SeasonStatus.Active,
    createdAt: '2024-11-01T10:00:00Z',
    updatedAt: '2024-11-01T10:00:00Z',
  },
  {
    id: 'SEASON003',
    name: 'Low Season',
    startDate: '2024-01-15',
    endDate: '2024-03-15',
    adjustmentType: PriceAdjustmentType.Percentage,
    adjustmentValue: -10,
    status: SeasonStatus.Inactive,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
]

export const MOCK_PRICE_HISTORY: PriceHistory[] = [
  {
    id: 'PH001',
    roomType: 'Standard King',
    oldPrice: 140,
    newPrice: 150,
    changedAt: '2024-07-01T10:00:00Z',
    changedBy: 'Admin',
    reason: 'Annual price adjustment',
  },
  {
    id: 'PH002',
    roomType: 'Deluxe Queen',
    oldPrice: 190,
    newPrice: 200,
    changedAt: '2024-07-01T10:00:00Z',
    changedBy: 'Admin',
    reason: 'Annual price adjustment',
  },
]

// Channel Management Mock Data
export const MOCK_CHANNELS: Channel[] = [
  {
    id: 'CH001',
    name: 'Booking.com',
    type: ChannelType.OTA,
    commissionRate: 15,
    status: ChannelStatus.Active,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'CH002',
    name: 'Expedia',
    type: ChannelType.OTA,
    commissionRate: 18,
    status: ChannelStatus.Active,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'CH003',
    name: 'Website',
    type: ChannelType.Website,
    commissionRate: 0,
    status: ChannelStatus.Active,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'CH004',
    name: 'Corporate Travel',
    type: ChannelType.Corporate,
    commissionRate: 10,
    status: ChannelStatus.Active,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'CH005',
    name: 'Travel Agent Network',
    type: ChannelType.TravelAgent,
    commissionRate: 12,
    status: ChannelStatus.Inactive,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
]

export const MOCK_CHANNEL_PERFORMANCE: ChannelPerformance[] = [
  {
    channelId: 'CH001',
    channelName: 'Booking.com',
    totalReservations: 45,
    totalRevenue: 85000,
    commissionAmount: 12750,
    profitAmount: 72250,
    revenueContributionPercent: 35,
    averageRoomPrice: 1888.89,
    bookingVolume: 45,
  },
  {
    channelId: 'CH002',
    channelName: 'Expedia',
    totalReservations: 32,
    totalRevenue: 62000,
    commissionAmount: 11160,
    profitAmount: 50840,
    revenueContributionPercent: 25.5,
    averageRoomPrice: 1937.50,
    bookingVolume: 32,
  },
  {
    channelId: 'CH003',
    channelName: 'Website',
    totalReservations: 78,
    totalRevenue: 95000,
    commissionAmount: 0,
    profitAmount: 95000,
    revenueContributionPercent: 39,
    averageRoomPrice: 1217.95,
    bookingVolume: 78,
  },
  {
    channelId: 'CH004',
    channelName: 'Corporate Travel',
    totalReservations: 15,
    totalRevenue: 28000,
    commissionAmount: 2800,
    profitAmount: 25200,
    revenueContributionPercent: 11.5,
    averageRoomPrice: 1866.67,
    bookingVolume: 15,
  },
]

// Invoice Mock Data
export const MOCK_INVOICES: Invoice[] = [
  {
    id: 'INV001',
    invoiceNumber: 'INV-2024-001',
    type: InvoiceType.Receipt,
    reservationId: 'RES001',
    guestId: 'G001',
    guestName: 'Alice Wonderland',
    guestEmail: 'alice@example.com',
    mealPlanCode: MealPlanCode.BB,
    status: InvoiceStatus.Paid,
    subtotal: 800,
    tax: 80,
    totalAmount: 880,
    paidAmount: 880,
    dueAmount: 0,
    paymentMethod: PaymentMethod.Online,
    issueDate: '2024-07-20',
    items: [
      {
        id: 'ITEM001',
        description: 'Room 101 - Standard King (5 nights)',
        quantity: 5,
        unitPrice: 150,
        tax: 75,
        total: 750,
      },
      {
        id: 'ITEM002',
        description: 'Seasonal Adjustment',
        quantity: 1,
        unitPrice: 50,
        tax: 5,
        total: 50,
      },
    ],
    createdAt: '2024-07-20T14:00:00Z',
    updatedAt: '2024-07-20T14:00:00Z',
  },
  {
    id: 'INV002',
    invoiceNumber: 'INV-2024-002',
    type: InvoiceType.Proforma,
    reservationId: 'RES002',
    guestId: 'G002',
    guestName: 'Bob The Builder',
    guestEmail: 'bob@example.com',
    mealPlanCode: MealPlanCode.FB,
    status: InvoiceStatus.Pending,
    subtotal: 1750,
    tax: 175,
    totalAmount: 1925,
    paidAmount: 500,
    dueAmount: 1425,
    paymentMethod: PaymentMethod.Card,
    issueDate: '2024-07-18',
    expiryDate: '2024-07-28',
    items: [
      {
        id: 'ITEM003',
        description: 'Room 201 - Suite (5 nights)',
        quantity: 5,
        unitPrice: 350,
        tax: 175,
        total: 1750,
      },
    ],
    createdAt: '2024-07-18T09:30:00Z',
    updatedAt: '2024-07-18T09:30:00Z',
  },
  {
    id: 'INV003',
    invoiceNumber: 'INV-2024-003',
    type: InvoiceType.Receipt,
    reservationId: 'RES003',
    guestId: 'G003',
    guestName: 'Charlie Chaplin',
    guestEmail: 'charlie@example.com',
    mealPlanCode: MealPlanCode.HB,
    status: InvoiceStatus.Paid,
    subtotal: 630,
    tax: 63,
    totalAmount: 693,
    paidAmount: 693,
    dueAmount: 0,
    paymentMethod: PaymentMethod.Cash,
    issueDate: '2024-07-18',
    items: [
      {
        id: 'ITEM004',
        description: 'Room 103 - Deluxe Queen (3 nights)',
        quantity: 3,
        unitPrice: 200,
        tax: 60,
        total: 600,
      },
      {
        id: 'ITEM005',
        description: 'Seasonal Adjustment',
        quantity: 1,
        unitPrice: 30,
        tax: 3,
        total: 30,
      },
    ],
    createdAt: '2024-07-18T11:00:00Z',
    updatedAt: '2024-07-18T11:00:00Z',
  },
  {
    id: 'INV004',
    invoiceNumber: 'INV-2024-004',
    type: InvoiceType.AdditionalBilling,
    reservationId: 'RES001',
    guestId: 'G001',
    guestName: 'Alice Wonderland',
    guestEmail: 'alice@example.com',
    mealPlanCode: MealPlanCode.BB,
    status: InvoiceStatus.Paid,
    subtotal: 150,
    tax: 15,
    totalAmount: 165,
    paidAmount: 165,
    dueAmount: 0,
    paymentMethod: PaymentMethod.Card,
    issueDate: '2024-07-22',
    items: [
      {
        id: 'ITEM006',
        description: 'Spa Services',
        quantity: 1,
        unitPrice: 100,
        tax: 10,
        total: 100,
      },
      {
        id: 'ITEM007',
        description: 'Room Service',
        quantity: 1,
        unitPrice: 50,
        tax: 5,
        total: 50,
      },
    ],
    createdAt: '2024-07-22T16:00:00Z',
    updatedAt: '2024-07-22T16:00:00Z',
  },
]

export const MOCK_ADDITIONAL_BILLINGS: AdditionalBilling[] = [
  {
    id: 'AB001',
    reservationId: 'RES001',
    serviceName: 'Spa Services',
    date: '2024-07-22',
    amount: 100,
    tax: 10,
    totalAmount: 110,
    description: 'Full body massage',
    createdAt: '2024-07-22T14:00:00Z',
  },
  {
    id: 'AB002',
    reservationId: 'RES001',
    serviceName: 'Room Service',
    date: '2024-07-22',
    amount: 50,
    tax: 5,
    totalAmount: 55,
    description: 'Dinner service',
    createdAt: '2024-07-22T18:00:00Z',
  },
]

export const MOCK_REFUNDS: Refund[] = [
  {
    id: 'REF001',
    refundNumber: 'REF-2024-001',
    reservationId: 'RES005',
    guestId: 'G005',
    guestName: 'Eve Harrington',
    amount: 275,
    reason: 'Cancellation within policy',
    status: InvoiceStatus.Processed,
    processedDate: '2024-07-21',
    createdAt: '2024-07-21T10:00:00Z',
  },
]

export const MOCK_CREDIT_NOTES: CreditNote[] = [
  {
    id: 'CN001',
    creditNoteNumber: 'CN-2024-001',
    invoiceId: 'INV002',
    amount: 100,
    reason: 'Service discount',
    status: InvoiceStatus.Applied,
    issuedDate: '2024-07-19',
    appliedDate: '2024-07-19',
    createdAt: '2024-07-19T12:00:00Z',
  },
]

// Services Mock Data
export const MOCK_SERVICES: Service[] = [
  {
    id: 'SRV001',
    name: 'Room Service - Breakfast',
    shortDescription: 'In-room breakfast service',
    detailedDescription: 'Full breakfast menu delivered to your room. Includes continental and hot breakfast options.',
    category: ServiceCategory.FoodBeverage,
    pricingModel: PricingModel.PerPerson,
    price: 25,
    taxApplicable: true,
    taxRate: 10,
    status: ServiceStatus.Active,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'SRV002',
    name: 'Spa - Full Body Massage',
    shortDescription: 'Professional full body massage',
    detailedDescription: '60-minute full body massage with premium oils. Requires therapist availability.',
    category: ServiceCategory.Spa,
    pricingModel: PricingModel.FixedPrice,
    price: 100,
    taxApplicable: true,
    taxRate: 10,
    status: ServiceStatus.Active,
    dependencies: ['Therapist availability'],
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'SRV003',
    name: 'Laundry Service',
    shortDescription: 'Professional laundry and dry cleaning',
    detailedDescription: 'Same-day laundry service for your garments. Dry cleaning available.',
    category: ServiceCategory.Laundry,
    pricingModel: PricingModel.PerUnit,
    price: 15,
    taxApplicable: true,
    taxRate: 10,
    status: ServiceStatus.Active,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'SRV004',
    name: 'Airport Transfer',
    shortDescription: 'Airport pickup and drop-off service',
    detailedDescription: 'Comfortable vehicle transfer to/from airport. Available 24/7.',
    category: ServiceCategory.Transport,
    pricingModel: PricingModel.FixedPrice,
    price: 50,
    taxApplicable: true,
    taxRate: 10,
    status: ServiceStatus.Active,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'SRV005',
    name: 'Extra Bed',
    shortDescription: 'Additional bed for room',
    detailedDescription: 'Extra bed setup in your room. Includes linens and amenities.',
    category: ServiceCategory.Housekeeping,
    pricingModel: PricingModel.PerDay,
    price: 30,
    taxApplicable: true,
    taxRate: 10,
    status: ServiceStatus.Active,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'SRV006',
    name: 'Late Check-Out',
    shortDescription: 'Extended check-out time',
    detailedDescription: 'Extend your check-out time until 2 PM (subject to availability).',
    category: ServiceCategory.Other,
    pricingModel: PricingModel.FixedPrice,
    price: 40,
    taxApplicable: false,
    status: ServiceStatus.Active,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
]

export const MOCK_SERVICE_REQUESTS: ServiceRequest[] = [
  {
    id: 'REQ001',
    reservationId: 'RES001',
    roomId: 'R001',
    roomNumber: '101',
    guestId: 'G001',
    guestName: 'Alice Wonderland',
    serviceId: 'SRV002',
    serviceName: 'Spa - Full Body Massage',
    quantity: 1,
    status: ServiceRequestStatus.Completed,
    requestedDate: '2024-07-22',
    completedDate: '2024-07-22',
    responsibleDepartment: 'Spa',
    responsibleStaff: 'Spa Therapist',
    createdAt: '2024-07-22T10:00:00Z',
  },
  {
    id: 'REQ002',
    reservationId: 'RES001',
    roomId: 'R001',
    roomNumber: '101',
    guestId: 'G001',
    guestName: 'Alice Wonderland',
    serviceId: 'SRV001',
    serviceName: 'Room Service - Breakfast',
    quantity: 2,
    status: ServiceRequestStatus.InProgress,
    requestedDate: '2024-07-23',
    responsibleDepartment: 'Food & Beverage',
    responsibleStaff: 'Room Service Staff',
    createdAt: '2024-07-23T07:00:00Z',
  },
  {
    id: 'REQ003',
    reservationId: 'RES002',
    roomId: 'R004',
    roomNumber: '201',
    guestId: 'G002',
    guestName: 'Bob The Builder',
    serviceId: 'SRV004',
    serviceName: 'Airport Transfer',
    quantity: 1,
    status: ServiceRequestStatus.Pending,
    requestedDate: '2024-07-28',
    responsibleDepartment: 'Transport',
    createdAt: '2024-07-20T14:00:00Z',
  },
]

// Policies Mock Data
export const MOCK_HOTEL_POLICIES: HotelPolicy[] = [
  {
    id: 'POL001',
    type: PolicyType.CheckInOut,
    title: 'Check-In and Check-Out Times',
    description: 'Standard check-in and check-out policy for all guests.',
    rules: [
      'Check-in time: 3:00 PM',
      'Check-out time: 11:00 AM',
      'Early check-in subject to availability (additional charges may apply)',
      'Late check-out available upon request (additional charges may apply)',
    ],
    status: 'Active',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'POL002',
    type: PolicyType.ChildAccommodation,
    title: 'Child Accommodation Guidelines',
    description: 'Policies regarding children staying at the hotel.',
    rules: [
      'Children under 12 stay free when using existing bedding',
      'Children 12 and above are charged as adults',
      'Cribs available upon request (free of charge)',
      'Maximum 2 children per room',
    ],
    status: 'Active',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'POL003',
    type: PolicyType.ExtraBed,
    title: 'Extra Bed Pricing Rules',
    description: 'Pricing and availability for extra beds.',
    rules: [
      'Extra bed charge: $30 per night',
      'Subject to room capacity',
      'Must be requested at least 24 hours in advance',
      'Includes linens and amenities',
    ],
    status: 'Active',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'POL004',
    type: PolicyType.Identification,
    title: 'Guest Identification Requirements',
    description: 'Required identification for check-in.',
    rules: [
      'Valid government-issued photo ID required',
      'Passport required for international guests',
      'ID must match reservation name',
      'Copies may be retained for records',
    ],
    status: 'Active',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'POL005',
    type: PolicyType.Smoking,
    title: 'Smoking Policy',
    description: 'Hotel smoking regulations.',
    rules: [
      'Non-smoking hotel',
      'Smoking strictly prohibited in all rooms',
      'Designated smoking areas available',
      'Smoking fee: $200 for violations',
    ],
    status: 'Active',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'POL006',
    type: PolicyType.Pet,
    title: 'Pet Allowance Policy',
    description: 'Policies regarding pets in the hotel.',
    rules: [
      'Pets allowed in designated pet-friendly rooms only',
      'Pet fee: $50 per night',
      'Maximum 2 pets per room',
      'Pets must be leashed in common areas',
      'Owner responsible for any damages',
    ],
    status: 'Active',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'POL007',
    type: PolicyType.MinimumStay,
    title: 'Minimum Stay Rules',
    description: 'Minimum night stay requirements.',
    rules: [
      'Weekend minimum: 2 nights',
      'Holiday season minimum: 3 nights',
      'Peak season minimum: 4 nights',
      'Subject to availability',
    ],
    status: 'Active',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
]

export const MOCK_CANCELLATION_POLICIES: CancellationPolicy[] = [
  {
    id: 'CAN001',
    name: 'Standard Cancellation Policy',
    deadlineHours: 24,
    penaltyType: PenaltyType.FirstNight,
    penaltyValue: 0,
    autoRefund: true,
    status: 'Active',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'CAN002',
    name: 'Non-Refundable Rate',
    deadlineHours: 0,
    penaltyType: PenaltyType.Percentage,
    penaltyValue: 100,
    autoRefund: false,
    status: 'Active',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'CAN003',
    name: 'Peak Season Policy',
    seasonId: 'SEASON001',
    deadlineHours: 48,
    penaltyType: PenaltyType.Percentage,
    penaltyValue: 50,
    autoRefund: false,
    status: 'Active',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'CAN004',
    name: 'OTA Cancellation Policy',
    channelId: 'CH001',
    deadlineHours: 24,
    penaltyType: PenaltyType.FixedFee,
    penaltyValue: 25,
    autoRefund: true,
    status: 'Active',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
]

export const MOCK_OVERBOOKING_POLICIES: OverbookingPolicy[] = [
  {
    id: 'OVB001',
    name: 'Standard Overbooking Policy',
    maxOverbookingPercent: 5,
    conditions: [
      'Based on historical no-show rates',
      'Requires credit card guarantee',
      'Subject to availability',
    ],
    requiresGuarantee: true,
    guaranteeType: 'PreAuthorization',
    status: 'Active',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'OVB002',
    name: 'Peak Season Overbooking',
    maxOverbookingPercent: 3,
    conditions: [
      'Peak season only',
      'Requires full advance payment',
      'Strict cancellation policy applies',
    ],
    requiresGuarantee: true,
    guaranteeType: 'AdvancePayment',
    applicableSeasons: ['SEASON001', 'SEASON002'],
    status: 'Active',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
]
